FROM node:alpine

COPY ./ /usr/share/app

WORKDIR /usr/share/app

ARG PORT
ARG HOST
ARG DEVE_DOMAIN
ARG PROD_DOMAIN
ARG AUTH0_CLIENT_ID
ARG AUTH0_CLIENT_DOMAIN
ARG MONGODB_ADDRESS_PROD
ARG MONGODB_USER
ARG MONGODB_PASS

ENV PORT=${PORT}
ENV HOST=${HOST}
ENV DEVE_DOMAIN=${DEVE_DOMAIN}
ENV PROD_DOMAIN=${PROD_DOMAIN}
ENV AUTH0_CLIENT_ID=${AUTH0_CLIENT_ID}
ENV AUTH0_CLIENT_DOMAIN=${AUTH0_CLIENT_DOMAIN}
ENV MONGODB_USER=${MONGODB_USER}
ENV MONGODB_PASS=${MONGODB_PASS}
ENV MONGODB_ADDRESS_PROD=${MONGODB_ADDRESS_PROD}

CMD yarn install && yarn start

EXPOSE 3000

